GET http://localhost:4004/odata/v4/order

###
GET http://localhost:4004/order/OrderSet(22222222-2222-2222-2222-222222222222)
###

GET http://localhost:4004/odata/v4/order/OrderSet
###

POST http://localhost:4004/odata/v4/order/OrderSet
Content-Type: application/json

{

      "orderDate": "2026-01-15",
      "totalAmount": 7800.75,
      "status": "Shipped",
      "createdAt": null,
      "createdBy": null
}

###
PUT http://localhost:4004/odata/v4/order/OrderSet(82cdfd9c-400c-4715-a3c4-3216c7113e14)
Content-Type: application/json

{
      "orderDate": "1098-01-15",
      "totalAmount": 900.75,
      "status": "Processing",
      "createdAt": null,
      "createdBy": null
}

###
DELETE GET http://localhost:4004/odata/v4/order

###
GET http://localhost:4004/order/OrderSet(22222222-2222-2222-2222-222222222222)
###

GET http://localhost:4004/odata/v4/order/OrderSet
###

POST http://localhost:4004/odata/v4/order/OrderSet
Content-Type: application/json

{

      "orderDate": "2026-01-15",
      "totalAmount": 7800.75,
      "status": "Shipped",
      "createdAt": null,
      "createdBy": null
}

###
PUT http://localhost:4004/odata/v4/order/OrderSet(82cdfd9c-400c-4715-a3c4-3216c7113e14)
Content-Type: application/json

{
      "orderDate": "1098-01-15",
      "totalAmount": 900.75,
      "status": "Processing",
      "createdAt": null,
      "createdBy": null
}

###
DELETE http://localhost:4004/odata/v4/order/OrderSet(82cdfd9c-400c-4715-a3c4-3216c7113e14)
